/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Eliminacion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Eliminacion#getSustantivo <em>Sustantivo</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Eliminacion#getTipoMaquina <em>Tipo Maquina</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Eliminacion#getPotencia <em>Potencia</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Eliminacion#getTipoMaterial <em>Tipo Material</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Eliminacion#getGrosor <em>Grosor</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEliminacion()
 * @model
 * @generated
 */
public interface Eliminacion extends EObject
{
  /**
   * Returns the value of the '<em><b>Sustantivo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sustantivo</em>' attribute.
   * @see #setSustantivo(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEliminacion_Sustantivo()
   * @model
   * @generated
   */
  String getSustantivo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Eliminacion#getSustantivo <em>Sustantivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sustantivo</em>' attribute.
   * @see #getSustantivo()
   * @generated
   */
  void setSustantivo(String value);

  /**
   * Returns the value of the '<em><b>Tipo Maquina</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo Maquina</em>' attribute.
   * @see #setTipoMaquina(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEliminacion_TipoMaquina()
   * @model
   * @generated
   */
  String getTipoMaquina();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Eliminacion#getTipoMaquina <em>Tipo Maquina</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo Maquina</em>' attribute.
   * @see #getTipoMaquina()
   * @generated
   */
  void setTipoMaquina(String value);

  /**
   * Returns the value of the '<em><b>Potencia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Potencia</em>' attribute.
   * @see #setPotencia(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEliminacion_Potencia()
   * @model
   * @generated
   */
  int getPotencia();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Eliminacion#getPotencia <em>Potencia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Potencia</em>' attribute.
   * @see #getPotencia()
   * @generated
   */
  void setPotencia(int value);

  /**
   * Returns the value of the '<em><b>Tipo Material</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo Material</em>' attribute.
   * @see #setTipoMaterial(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEliminacion_TipoMaterial()
   * @model
   * @generated
   */
  String getTipoMaterial();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Eliminacion#getTipoMaterial <em>Tipo Material</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo Material</em>' attribute.
   * @see #getTipoMaterial()
   * @generated
   */
  void setTipoMaterial(String value);

  /**
   * Returns the value of the '<em><b>Grosor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grosor</em>' attribute.
   * @see #setGrosor(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEliminacion_Grosor()
   * @model
   * @generated
   */
  int getGrosor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Eliminacion#getGrosor <em>Grosor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Grosor</em>' attribute.
   * @see #getGrosor()
   * @generated
   */
  void setGrosor(int value);

} // Eliminacion
