/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Procesos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PROCESOS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ProcesoImpl <em>Proceso</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ProcesoImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProceso()
   * @generated
   */
  int PROCESO = 1;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESO__TIPO = 0;

  /**
   * The feature id for the '<em><b>Creacion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESO__CREACION = 1;

  /**
   * The feature id for the '<em><b>Consulta</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESO__CONSULTA = 2;

  /**
   * The feature id for the '<em><b>Eliminacion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESO__ELIMINACION = 3;

  /**
   * The number of structural features of the '<em>Proceso</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESO_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CreacionImpl <em>Creacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CreacionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCreacion()
   * @generated
   */
  int CREACION = 2;

  /**
   * The feature id for the '<em><b>Sustantivo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREACION__SUSTANTIVO = 0;

  /**
   * The feature id for the '<em><b>Tipo Maquina</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREACION__TIPO_MAQUINA = 1;

  /**
   * The feature id for the '<em><b>Potencia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREACION__POTENCIA = 2;

  /**
   * The feature id for the '<em><b>Tipo Material</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREACION__TIPO_MATERIAL = 3;

  /**
   * The feature id for the '<em><b>Grosor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREACION__GROSOR = 4;

  /**
   * The number of structural features of the '<em>Creacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREACION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ConsultaImpl <em>Consulta</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ConsultaImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getConsulta()
   * @generated
   */
  int CONSULTA = 3;

  /**
   * The feature id for the '<em><b>Sustantivo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSULTA__SUSTANTIVO = 0;

  /**
   * The feature id for the '<em><b>Tipo Maquina</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSULTA__TIPO_MAQUINA = 1;

  /**
   * The feature id for the '<em><b>Potencia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSULTA__POTENCIA = 2;

  /**
   * The feature id for the '<em><b>Tipo Material</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSULTA__TIPO_MATERIAL = 3;

  /**
   * The feature id for the '<em><b>Grosor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSULTA__GROSOR = 4;

  /**
   * The feature id for the '<em><b>Verbo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSULTA__VERBO = 5;

  /**
   * The number of structural features of the '<em>Consulta</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSULTA_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.EliminacionImpl <em>Eliminacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.EliminacionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getEliminacion()
   * @generated
   */
  int ELIMINACION = 4;

  /**
   * The feature id for the '<em><b>Sustantivo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELIMINACION__SUSTANTIVO = 0;

  /**
   * The feature id for the '<em><b>Tipo Maquina</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELIMINACION__TIPO_MAQUINA = 1;

  /**
   * The feature id for the '<em><b>Potencia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELIMINACION__POTENCIA = 2;

  /**
   * The feature id for the '<em><b>Tipo Material</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELIMINACION__TIPO_MATERIAL = 3;

  /**
   * The feature id for the '<em><b>Grosor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELIMINACION__GROSOR = 4;

  /**
   * The number of structural features of the '<em>Eliminacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELIMINACION_FEATURE_COUNT = 5;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getProcesos <em>Procesos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Procesos</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getProcesos()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Procesos();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Proceso <em>Proceso</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Proceso</em>'.
   * @see org.xtext.example.mydsl.myDsl.Proceso
   * @generated
   */
  EClass getProceso();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Proceso#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see org.xtext.example.mydsl.myDsl.Proceso#getTipo()
   * @see #getProceso()
   * @generated
   */
  EAttribute getProceso_Tipo();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Proceso#getCreacion <em>Creacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Creacion</em>'.
   * @see org.xtext.example.mydsl.myDsl.Proceso#getCreacion()
   * @see #getProceso()
   * @generated
   */
  EReference getProceso_Creacion();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Proceso#getConsulta <em>Consulta</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Consulta</em>'.
   * @see org.xtext.example.mydsl.myDsl.Proceso#getConsulta()
   * @see #getProceso()
   * @generated
   */
  EReference getProceso_Consulta();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Proceso#getEliminacion <em>Eliminacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Eliminacion</em>'.
   * @see org.xtext.example.mydsl.myDsl.Proceso#getEliminacion()
   * @see #getProceso()
   * @generated
   */
  EReference getProceso_Eliminacion();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Creacion <em>Creacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Creacion</em>'.
   * @see org.xtext.example.mydsl.myDsl.Creacion
   * @generated
   */
  EClass getCreacion();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Creacion#getSustantivo <em>Sustantivo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sustantivo</em>'.
   * @see org.xtext.example.mydsl.myDsl.Creacion#getSustantivo()
   * @see #getCreacion()
   * @generated
   */
  EAttribute getCreacion_Sustantivo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Creacion#getTipoMaquina <em>Tipo Maquina</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Maquina</em>'.
   * @see org.xtext.example.mydsl.myDsl.Creacion#getTipoMaquina()
   * @see #getCreacion()
   * @generated
   */
  EAttribute getCreacion_TipoMaquina();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Creacion#getPotencia <em>Potencia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Potencia</em>'.
   * @see org.xtext.example.mydsl.myDsl.Creacion#getPotencia()
   * @see #getCreacion()
   * @generated
   */
  EAttribute getCreacion_Potencia();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Creacion#getTipoMaterial <em>Tipo Material</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Material</em>'.
   * @see org.xtext.example.mydsl.myDsl.Creacion#getTipoMaterial()
   * @see #getCreacion()
   * @generated
   */
  EAttribute getCreacion_TipoMaterial();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Creacion#getGrosor <em>Grosor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Grosor</em>'.
   * @see org.xtext.example.mydsl.myDsl.Creacion#getGrosor()
   * @see #getCreacion()
   * @generated
   */
  EAttribute getCreacion_Grosor();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Consulta <em>Consulta</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Consulta</em>'.
   * @see org.xtext.example.mydsl.myDsl.Consulta
   * @generated
   */
  EClass getConsulta();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Consulta#getSustantivo <em>Sustantivo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sustantivo</em>'.
   * @see org.xtext.example.mydsl.myDsl.Consulta#getSustantivo()
   * @see #getConsulta()
   * @generated
   */
  EAttribute getConsulta_Sustantivo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Consulta#getTipoMaquina <em>Tipo Maquina</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Maquina</em>'.
   * @see org.xtext.example.mydsl.myDsl.Consulta#getTipoMaquina()
   * @see #getConsulta()
   * @generated
   */
  EAttribute getConsulta_TipoMaquina();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Consulta#getPotencia <em>Potencia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Potencia</em>'.
   * @see org.xtext.example.mydsl.myDsl.Consulta#getPotencia()
   * @see #getConsulta()
   * @generated
   */
  EAttribute getConsulta_Potencia();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Consulta#getTipoMaterial <em>Tipo Material</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Material</em>'.
   * @see org.xtext.example.mydsl.myDsl.Consulta#getTipoMaterial()
   * @see #getConsulta()
   * @generated
   */
  EAttribute getConsulta_TipoMaterial();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Consulta#getGrosor <em>Grosor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Grosor</em>'.
   * @see org.xtext.example.mydsl.myDsl.Consulta#getGrosor()
   * @see #getConsulta()
   * @generated
   */
  EAttribute getConsulta_Grosor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Consulta#getVerbo <em>Verbo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Verbo</em>'.
   * @see org.xtext.example.mydsl.myDsl.Consulta#getVerbo()
   * @see #getConsulta()
   * @generated
   */
  EAttribute getConsulta_Verbo();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Eliminacion <em>Eliminacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Eliminacion</em>'.
   * @see org.xtext.example.mydsl.myDsl.Eliminacion
   * @generated
   */
  EClass getEliminacion();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Eliminacion#getSustantivo <em>Sustantivo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sustantivo</em>'.
   * @see org.xtext.example.mydsl.myDsl.Eliminacion#getSustantivo()
   * @see #getEliminacion()
   * @generated
   */
  EAttribute getEliminacion_Sustantivo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Eliminacion#getTipoMaquina <em>Tipo Maquina</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Maquina</em>'.
   * @see org.xtext.example.mydsl.myDsl.Eliminacion#getTipoMaquina()
   * @see #getEliminacion()
   * @generated
   */
  EAttribute getEliminacion_TipoMaquina();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Eliminacion#getPotencia <em>Potencia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Potencia</em>'.
   * @see org.xtext.example.mydsl.myDsl.Eliminacion#getPotencia()
   * @see #getEliminacion()
   * @generated
   */
  EAttribute getEliminacion_Potencia();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Eliminacion#getTipoMaterial <em>Tipo Material</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Material</em>'.
   * @see org.xtext.example.mydsl.myDsl.Eliminacion#getTipoMaterial()
   * @see #getEliminacion()
   * @generated
   */
  EAttribute getEliminacion_TipoMaterial();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Eliminacion#getGrosor <em>Grosor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Grosor</em>'.
   * @see org.xtext.example.mydsl.myDsl.Eliminacion#getGrosor()
   * @see #getEliminacion()
   * @generated
   */
  EAttribute getEliminacion_Grosor();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Procesos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PROCESOS = eINSTANCE.getModel_Procesos();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ProcesoImpl <em>Proceso</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ProcesoImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProceso()
     * @generated
     */
    EClass PROCESO = eINSTANCE.getProceso();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESO__TIPO = eINSTANCE.getProceso_Tipo();

    /**
     * The meta object literal for the '<em><b>Creacion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESO__CREACION = eINSTANCE.getProceso_Creacion();

    /**
     * The meta object literal for the '<em><b>Consulta</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESO__CONSULTA = eINSTANCE.getProceso_Consulta();

    /**
     * The meta object literal for the '<em><b>Eliminacion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESO__ELIMINACION = eINSTANCE.getProceso_Eliminacion();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CreacionImpl <em>Creacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CreacionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCreacion()
     * @generated
     */
    EClass CREACION = eINSTANCE.getCreacion();

    /**
     * The meta object literal for the '<em><b>Sustantivo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREACION__SUSTANTIVO = eINSTANCE.getCreacion_Sustantivo();

    /**
     * The meta object literal for the '<em><b>Tipo Maquina</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREACION__TIPO_MAQUINA = eINSTANCE.getCreacion_TipoMaquina();

    /**
     * The meta object literal for the '<em><b>Potencia</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREACION__POTENCIA = eINSTANCE.getCreacion_Potencia();

    /**
     * The meta object literal for the '<em><b>Tipo Material</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREACION__TIPO_MATERIAL = eINSTANCE.getCreacion_TipoMaterial();

    /**
     * The meta object literal for the '<em><b>Grosor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREACION__GROSOR = eINSTANCE.getCreacion_Grosor();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ConsultaImpl <em>Consulta</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ConsultaImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getConsulta()
     * @generated
     */
    EClass CONSULTA = eINSTANCE.getConsulta();

    /**
     * The meta object literal for the '<em><b>Sustantivo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSULTA__SUSTANTIVO = eINSTANCE.getConsulta_Sustantivo();

    /**
     * The meta object literal for the '<em><b>Tipo Maquina</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSULTA__TIPO_MAQUINA = eINSTANCE.getConsulta_TipoMaquina();

    /**
     * The meta object literal for the '<em><b>Potencia</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSULTA__POTENCIA = eINSTANCE.getConsulta_Potencia();

    /**
     * The meta object literal for the '<em><b>Tipo Material</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSULTA__TIPO_MATERIAL = eINSTANCE.getConsulta_TipoMaterial();

    /**
     * The meta object literal for the '<em><b>Grosor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSULTA__GROSOR = eINSTANCE.getConsulta_Grosor();

    /**
     * The meta object literal for the '<em><b>Verbo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSULTA__VERBO = eINSTANCE.getConsulta_Verbo();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.EliminacionImpl <em>Eliminacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.EliminacionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getEliminacion()
     * @generated
     */
    EClass ELIMINACION = eINSTANCE.getEliminacion();

    /**
     * The meta object literal for the '<em><b>Sustantivo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELIMINACION__SUSTANTIVO = eINSTANCE.getEliminacion_Sustantivo();

    /**
     * The meta object literal for the '<em><b>Tipo Maquina</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELIMINACION__TIPO_MAQUINA = eINSTANCE.getEliminacion_TipoMaquina();

    /**
     * The meta object literal for the '<em><b>Potencia</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELIMINACION__POTENCIA = eINSTANCE.getEliminacion_Potencia();

    /**
     * The meta object literal for the '<em><b>Tipo Material</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELIMINACION__TIPO_MATERIAL = eINSTANCE.getEliminacion_TipoMaterial();

    /**
     * The meta object literal for the '<em><b>Grosor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELIMINACION__GROSOR = eINSTANCE.getEliminacion_Grosor();

  }

} //MyDslPackage
