/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Proceso</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Proceso#getTipo <em>Tipo</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Proceso#getCreacion <em>Creacion</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Proceso#getConsulta <em>Consulta</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Proceso#getEliminacion <em>Eliminacion</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProceso()
 * @model
 * @generated
 */
public interface Proceso extends EObject
{
  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see #setTipo(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProceso_Tipo()
   * @model
   * @generated
   */
  String getTipo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Proceso#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see #getTipo()
   * @generated
   */
  void setTipo(String value);

  /**
   * Returns the value of the '<em><b>Creacion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Creacion</em>' containment reference.
   * @see #setCreacion(Creacion)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProceso_Creacion()
   * @model containment="true"
   * @generated
   */
  Creacion getCreacion();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Proceso#getCreacion <em>Creacion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Creacion</em>' containment reference.
   * @see #getCreacion()
   * @generated
   */
  void setCreacion(Creacion value);

  /**
   * Returns the value of the '<em><b>Consulta</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consulta</em>' containment reference.
   * @see #setConsulta(Consulta)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProceso_Consulta()
   * @model containment="true"
   * @generated
   */
  Consulta getConsulta();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Proceso#getConsulta <em>Consulta</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consulta</em>' containment reference.
   * @see #getConsulta()
   * @generated
   */
  void setConsulta(Consulta value);

  /**
   * Returns the value of the '<em><b>Eliminacion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eliminacion</em>' containment reference.
   * @see #setEliminacion(Eliminacion)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProceso_Eliminacion()
   * @model containment="true"
   * @generated
   */
  Eliminacion getEliminacion();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Proceso#getEliminacion <em>Eliminacion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eliminacion</em>' containment reference.
   * @see #getEliminacion()
   * @generated
   */
  void setEliminacion(Eliminacion value);

} // Proceso
