/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.Eliminacion;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Eliminacion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EliminacionImpl#getSustantivo <em>Sustantivo</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EliminacionImpl#getTipoMaquina <em>Tipo Maquina</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EliminacionImpl#getPotencia <em>Potencia</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EliminacionImpl#getTipoMaterial <em>Tipo Material</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EliminacionImpl#getGrosor <em>Grosor</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EliminacionImpl extends MinimalEObjectImpl.Container implements Eliminacion
{
  /**
   * The default value of the '{@link #getSustantivo() <em>Sustantivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSustantivo()
   * @generated
   * @ordered
   */
  protected static final String SUSTANTIVO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSustantivo() <em>Sustantivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSustantivo()
   * @generated
   * @ordered
   */
  protected String sustantivo = SUSTANTIVO_EDEFAULT;

  /**
   * The default value of the '{@link #getTipoMaquina() <em>Tipo Maquina</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoMaquina()
   * @generated
   * @ordered
   */
  protected static final String TIPO_MAQUINA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTipoMaquina() <em>Tipo Maquina</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoMaquina()
   * @generated
   * @ordered
   */
  protected String tipoMaquina = TIPO_MAQUINA_EDEFAULT;

  /**
   * The default value of the '{@link #getPotencia() <em>Potencia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPotencia()
   * @generated
   * @ordered
   */
  protected static final int POTENCIA_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPotencia() <em>Potencia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPotencia()
   * @generated
   * @ordered
   */
  protected int potencia = POTENCIA_EDEFAULT;

  /**
   * The default value of the '{@link #getTipoMaterial() <em>Tipo Material</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoMaterial()
   * @generated
   * @ordered
   */
  protected static final String TIPO_MATERIAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTipoMaterial() <em>Tipo Material</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoMaterial()
   * @generated
   * @ordered
   */
  protected String tipoMaterial = TIPO_MATERIAL_EDEFAULT;

  /**
   * The default value of the '{@link #getGrosor() <em>Grosor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGrosor()
   * @generated
   * @ordered
   */
  protected static final int GROSOR_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getGrosor() <em>Grosor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGrosor()
   * @generated
   * @ordered
   */
  protected int grosor = GROSOR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EliminacionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ELIMINACION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSustantivo()
  {
    return sustantivo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSustantivo(String newSustantivo)
  {
    String oldSustantivo = sustantivo;
    sustantivo = newSustantivo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ELIMINACION__SUSTANTIVO, oldSustantivo, sustantivo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTipoMaquina()
  {
    return tipoMaquina;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoMaquina(String newTipoMaquina)
  {
    String oldTipoMaquina = tipoMaquina;
    tipoMaquina = newTipoMaquina;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ELIMINACION__TIPO_MAQUINA, oldTipoMaquina, tipoMaquina));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPotencia()
  {
    return potencia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPotencia(int newPotencia)
  {
    int oldPotencia = potencia;
    potencia = newPotencia;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ELIMINACION__POTENCIA, oldPotencia, potencia));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTipoMaterial()
  {
    return tipoMaterial;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoMaterial(String newTipoMaterial)
  {
    String oldTipoMaterial = tipoMaterial;
    tipoMaterial = newTipoMaterial;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ELIMINACION__TIPO_MATERIAL, oldTipoMaterial, tipoMaterial));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getGrosor()
  {
    return grosor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGrosor(int newGrosor)
  {
    int oldGrosor = grosor;
    grosor = newGrosor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ELIMINACION__GROSOR, oldGrosor, grosor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ELIMINACION__SUSTANTIVO:
        return getSustantivo();
      case MyDslPackage.ELIMINACION__TIPO_MAQUINA:
        return getTipoMaquina();
      case MyDslPackage.ELIMINACION__POTENCIA:
        return getPotencia();
      case MyDslPackage.ELIMINACION__TIPO_MATERIAL:
        return getTipoMaterial();
      case MyDslPackage.ELIMINACION__GROSOR:
        return getGrosor();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ELIMINACION__SUSTANTIVO:
        setSustantivo((String)newValue);
        return;
      case MyDslPackage.ELIMINACION__TIPO_MAQUINA:
        setTipoMaquina((String)newValue);
        return;
      case MyDslPackage.ELIMINACION__POTENCIA:
        setPotencia((Integer)newValue);
        return;
      case MyDslPackage.ELIMINACION__TIPO_MATERIAL:
        setTipoMaterial((String)newValue);
        return;
      case MyDslPackage.ELIMINACION__GROSOR:
        setGrosor((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ELIMINACION__SUSTANTIVO:
        setSustantivo(SUSTANTIVO_EDEFAULT);
        return;
      case MyDslPackage.ELIMINACION__TIPO_MAQUINA:
        setTipoMaquina(TIPO_MAQUINA_EDEFAULT);
        return;
      case MyDslPackage.ELIMINACION__POTENCIA:
        setPotencia(POTENCIA_EDEFAULT);
        return;
      case MyDslPackage.ELIMINACION__TIPO_MATERIAL:
        setTipoMaterial(TIPO_MATERIAL_EDEFAULT);
        return;
      case MyDslPackage.ELIMINACION__GROSOR:
        setGrosor(GROSOR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ELIMINACION__SUSTANTIVO:
        return SUSTANTIVO_EDEFAULT == null ? sustantivo != null : !SUSTANTIVO_EDEFAULT.equals(sustantivo);
      case MyDslPackage.ELIMINACION__TIPO_MAQUINA:
        return TIPO_MAQUINA_EDEFAULT == null ? tipoMaquina != null : !TIPO_MAQUINA_EDEFAULT.equals(tipoMaquina);
      case MyDslPackage.ELIMINACION__POTENCIA:
        return potencia != POTENCIA_EDEFAULT;
      case MyDslPackage.ELIMINACION__TIPO_MATERIAL:
        return TIPO_MATERIAL_EDEFAULT == null ? tipoMaterial != null : !TIPO_MATERIAL_EDEFAULT.equals(tipoMaterial);
      case MyDslPackage.ELIMINACION__GROSOR:
        return grosor != GROSOR_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (sustantivo: ");
    result.append(sustantivo);
    result.append(", tipoMaquina: ");
    result.append(tipoMaquina);
    result.append(", potencia: ");
    result.append(potencia);
    result.append(", tipoMaterial: ");
    result.append(tipoMaterial);
    result.append(", grosor: ");
    result.append(grosor);
    result.append(')');
    return result.toString();
  }

} //EliminacionImpl
